- name: Build AAR
      run: bash ./build.sh android-aar release
    - name: Find and Copy AAR
      run: |
        mkdir -p dist
        find . -name "*.aar" -exec cp {} dist/ \;
    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with:
        name: libzt-release-aar
        path: dist/
